name: PlanetaryMaps
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy=2.1.3
  - matplotlib=3.9.2
  - pygmt=0.13.0
  - xarray=2024.10.0
  - gdown=5.1.0
  # Optional dependencies
  
